### ISSUE TITLE
Error while login in

### ISSUE THREAD

**Issue by NextGenZ** [Tustin/fortnite-php#2]
```php
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/893913b952a44596ab99414dc183cf2a/client/QueryProfile?profileId=athena&rvn=-1` resulted in a `403 Forbidden` response: {"errorCode":"errors.com.epicgames.common.missing_action","errorMessage":"Login is banned or does not posses the action (truncated...) ' in /home/xpolishp/public_html/addon/xpolish.pl/discordbot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/xpolishp/public_html/addon/xpolish.pl/discordbot/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/xpolishp/public_html/addon/xpolish.pl/discordbot/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/xpolishp/public_html/addon/xpolish.pl/disc in /home/xpolishp/public_html/addon/xpolish.pl/discordbot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by Tustin** [comment]
Pretty sure this is the error you get if you've never loaded Fortnite on your account. Try that and see if it works.

**Comment by NextGenZ** [comment]
```java
Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/xpolishp/public_html/addon/xpolish.pl/discordbot/vendor/tustin/fortnite-php/src/Stats.php on line 96

**Comment by Tustin** [comment]
Update PHP to the latest version.

**Comment by R0GUEx** [comment]
It looks like guzzle is missing on your php server. Install it via composer.
https://github.com/guzzle/guzzle
https://getcomposer.org/download/

**Comment by Tustin** [comment]
@R0GUEx that doesn't seem to be the problem because in the initial issue, he got the JSON response from the server. I looked at where the second error he got was at and it has to do with a PHP 7.x feature.

**Comment by NextGenZ** [comment]
Thanks fixed.
