### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by MagicalMouse39** [Tustin/fortnite-php#46]
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/62d343e3caea47e881e8919e31b8f1ac/client/QueryProfile?profileId=athena&rvn=-1` resulted in a `403 Forbidden` response: {"errorCode":"errors.com.epicgames.common.missing_action","errorMessage":"Login is banned or does not posses the action (truncated...) in E:\Programmi\XAMPP\htdocs\provaTinti\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 E:\Programmi\XAMPP\htdocs\provaTinti\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 E:\Programmi\XAMPP\htdocs\provaTinti\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 E:\Programmi\XAMPP\htdocs\provaTinti\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, in E:\Programmi\XAMPP\htdocs\provaTinti\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by koflin** [comment]
I've got the exact same error.

**Comment by Trexon25** [comment]
same.
